CHANGELOG, framework/db/ar/CActiveFinder.php
This issue was introduced with `1.1.16` and fixed `Bug #268: Fixed Active Record count error when some field name starting from 'count' (nineinchnick)`
=> Fixes #3696 with broken case insensitiveness for Active Record count expressions

tests/framework/validators/CExistValidatorTest.php, tests/framework/validators/CUniqueValidatorTest.php
I found how could be reproduced the error. If you do not have installed "php5-sqlite" extension and run the tests the error will rise, even in the code is placed check for existing php sqllite installation in the same class take a look at "setUp" method.
Bug fix applied:
Affected files: 
tests/framework/validators/CExistValidatorTest.php
tests/framework/validators/CUniqueValidatorTest.php
4a7127b..16410a6  master -> master
Fix for #3819
=> Fix for #3819

CHANGELOG, framework/zii/widgets/assets/gridview/jquery.yiigridview.js
When updating grid with a POST request, and the request data is not provided and thus is collected from form with the jQuery `.serialize()` method, the script fails at [this line](https://github.com/yiisoft/yii/blob/8c30239dce366a70bc7486cd605c00c4938f0c9e/framework/zii/widgets/assets/gridview/jquery.yiigridview.js#L366) because `options.data` is a string at this point and can't act as an argument for `$.each()`. This fix makes `options.data` a plain object instead of a string in the described circumstances.
=> Bug fix in jQuery Yii GridView plugin

framework/i18n/gettext/CGettextMoFile.php
Only variables should be passed by reference.
=> Rearranged current() calls to comply with PHP strict standards.

CHANGELOG, framework/web/CHttpRequest.php
Enh #3457
Originally, REST requests such as PUT, PATCH and DELETE  had their body parsed using `mb_parse_str()` or `parse_str()`, which means that JSON data would not be properly parsed.
The merge is basically a backport of the solution existing in Yii 2. It will add `CJSON::decode()` to the possible parsing functions, activated only if the request's content type is `application/json`. This content type can be retrieved by the new public function `getContentType()`.
In addition, as in Yii 2, the JSON decoding function can be configured to use associative arrays (by default) for JSON object data, according to the new boolean property `$jsonAsArray`.
=> Enh #3457: CHttpRequest able to decode JSON REST parameters.

CHANGELOG, framework/web/helpers/CHtml.php
This PR fix bug, when CHtml render active hidden filed for disabled checbox or radio buttons.
```php
echo CHtml::activeCheckBox($model, 'active', array('disabled' => true));
```
=> Inherit "disabled" attribute in internally rendered hidden fields in checkbox, radio, etc.

framework/caching/CRedisCache.php
try {
Yii::app()->redisCache->executeCommand('INCR', ["key"]);
} catch (Exception $e) {
//catch the exception
}
try {
Yii::app()->redisCache->executeCommand('GET', ["key"]);//[error] [php] fwrite() expects parameter 1 to be resource, boolean given 
} catch (Exception $e) {
}
=> Fix CRedisCache::executeCommand() error when the previous connection timeout exception was catched

.gitignore, .travis.yml, composer.json, framework/vendors/TextHighlighter/Text/Highlighter.php, framework/vendors/TextHighlighter/Text/Highlighter/Renderer/Array.php, framework/vendors/TextHighlighter/Text/Highlighter/Renderer/Html.php, tests/bootstrap.php, tests/travis/memcache-setup.sh
Mainly build environment adjustments to make sure tests run fine. Additionally some fixes in TextHighlighter:
- adjusted `TextHighlighter` to load fine with constants.
- adjusted `TextHighlighter` to work the same on PHP 7.1. as on other versions by introducing an explicit cast to array() which is not allowed to be implicit anymore in PHP 7.1.
Is there an upstream repo of the TextHighlighter where we could contribute these back?
=> PHP 7.1 compatibility

.travis.yml
| Fixed issues  | speeds up the hhvm unit tests
Turn off the hhvm JIT to speed up the hhvm unit tests.
Source for why the JIT is bad for unit testing: facebook/hhvm#6979
=> Speed up hhvm unit tests - disable jit

CHANGELOG, framework/web/CDbHttpSession.php
Updating from PHP 5.6 to PHP 7.1 introduced an issue where the session data no longer was updating, preventing the user from logging in. After debugging it was discovered the queryScalar in the readSession function was returning NULL from the empty record/row in the database with the passed in session ID.  The return statement has a strict comparison to check for boolean false, and did not account for a NULL value being returned from the empty "data" column in the database.  Changing the return statement to also check for a NULL resolves this issue, and will allow the session data to be updated correctly.  The config for the session is using CDbHttpSession class with a custom session name, and a CDbConnection that connects to IBM DB2 database.
Note that only PHP 7 compatibility fixes are …
=> Session data not updating after login

docs/guide/de/topics.i18n.txt, docs/guide/id/topics.i18n.txt, docs/guide/ja/topics.i18n.txt, docs/guide/pl/topics.i18n.txt, docs/guide/ru/topics.i18n.txt, docs/guide/sv/topics.i18n.txt, docs/guide/topics.i18n.txt, docs/guide/uk/topics.i18n.txt
| Is bugfix?    | no
I've not changed code, only docs.
Replaced old deprecated link:
http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html 
with new one:
http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html
=> docs [docs/guide/topics.i18n.txt] fix URL to "Language Plural Rules"

CHANGELOG, framework/db/schema/mysql/CMysqlColumnSchema.php
| Tests pass?   | yes, i think
| Fixed issues  | #4179
=> #4179 Fix MariaDB 10.2 current_timestamp()

CHANGELOG, framework/YiiBase.php, framework/web/CHttpSession.php, framework/web/helpers/CHtml.php, tests/TestAutoloader.php, tests/framework/web/CHttpSessionTest.php
Add filters  for YiiBase::autoloader autoloader that allows to skip autoloading for specific classes.
| New feature?  | yes
I will try to describe problem that i found in my project and I cannot fix it. 
I have legacy project in PHP5.6. This is enormous application. We cannot migrate to Yii2 at the moment.
I am trying to upgrade PHP to 7.2. We use Smarty 3.1.12 and it use a lot of deprecated and removed in php 7.2 stuff. I upgraded Smarty to 3.1.31(latest). 
We have got set …
=> Filters  for YiiBase::autoloader autoloader

CHANGELOG, framework/gii/components/Pear/Text/Diff/Engine/native.php, framework/gii/components/Pear/Text/Diff/Engine/shell.php
Changed uses of assert with string arguments to expressions which fixes #4197
| Fixed issues  | 4197
=> Fixed PHP 7.2 assert with string argument is deprecated warning using Gii

framework/gii/components/Pear/Text/Diff/Engine/native.php, framework/web/widgets/CTabView.php
- Fixed each usages in CTabView.php
- Fixed each usages in native.php
=> Fixed: PHP 7.2 each() function in CTabView is deprecated #4199

CHANGELOG, framework/db/schema/mssql/CMssqlSqlsrvPdoAdapter.php
If SQLSRV version is >= 5 then the lastInsertId function will be called without parameters, maintaining the workaround for the old versions. 
| Fixed issues  | #4198
=> Fixed: PHP 7.2 sqlserver lastInsertId #4198

framework/web/widgets/CTabView.php
=> Fixed: activeTab was not selected in CTabView

framework/db/schema/mssql/CMssqlSqlsrvPdoAdapter.php
not a PHP 7.2 fix per se, but the bug was introduced in #4198 (which fixed a PHP 7.2 issue)
| Fixed issues  | <a href="https://github.com/yiisoft/yii/issues/4198#issuecomment-394151912">#4198 (comment)</a>
=> fix PHP 5.1 incomp. in CMssqlSqlsrvPdoAdapter caused by PHP 7.2 fix

CHANGELOG, composer.json
As of php-7.2 mcrypt extension moved to pecl.
But it's required to use CSecurityManager.
| Fixed issues  | #4182
=> WIP: Quick fix #4182 - mcrypt dependency

CHANGELOG, framework/web/js/source/jquery.yiiactiveform.js
remove deprecation errors from framework/web/js/source/jquery.yiiactiveform.js  when using jQuery3.1.1
jquery.yiiactiveform.js has some issues in it that are highlighted when using jquery3.1.1 instead of old jquery1.12.4 library. 
Important as there are security issues in 1.12.4.
This PR fixes them.
=> Fix deprecation error in jquery3.x by not using shortcuts.

CHANGELOG, framework/web/helpers/CJavaScript.php, tests/framework/web/helpers/CJavaScriptTest.php
Add backward compatibility to do not escape null value. As it was before Yii 1.1.20
| Fixed issues  | #4238
=> Update CJavaScript::quote to accept null value. Backward compatibility change.

composer.json
Ref #4232
| Tests pass?   | CI will check
| Fixed issues  | 4232
=> Add `phpseclib/mcrypt_compat` polyfill as `require-dev`

CHANGELOG, tests/compatibility.php
=> Fixes yiisoft#4227: Fixed incompatibility with PHPUnit6

CHANGELOG, framework/gii/components/Pear/Text/Diff3.php, framework/vendors/markdown/markdown.php
Bug #4256: PHP 7 compatibility issues: PHP4 style constructor in Pear/Text/Diff3.php and create_function() in markdown/markdown.php (kenguest)
=> #4256: PHP 7 compatibility issues.

.travis.yml, tests/travis/memcache-setup.sh
I am preparing this PR. phpenv does not want to install 7.4 currently, so I'll wait until it does.
If you have any additions for PHP 7.4 support, feel free.
The amount of skipped tests intrigues me a bit. Are they all ok?
=> add php 7.4

framework/web/helpers/CHtml.php
`CHtml::modelName()` (used by all these functions) supports also `string` as a `$model`.
=> Update phpdoc in CHtml

CHANGELOG, framework/vendors/markdown/markdown.php
=> Fix #4256: Fixed deprecated usage of create_function() in markdown.php

CHANGELOG, framework/validators/CUrlValidator.php
=> Fix #4291: The scheme(protocol) is deleted when validateIDN is enabled after validation

CHANGELOG, framework/db/schema/pgsql/CPgsqlSchema.php
Add PostgreSQL 12 support.
From PostgreSQL 12 [changelog](https://www.postgresql.org/docs/release/12.0/):
- Remove obsolete pg_constraint.consrc column (Peter Eisentraut)
- Remove obsolete pg_attrdef.adsrc column (Peter Eisentraut)
| Fixed issues  | #4294
=> Add PostgreSQL 12 support, rel #4294

CHANGELOG, framework/caching/CMemCache.php
There is an issue with Yii1 and memcached that has already been addressed in yii2. The issue is related to internal memcached clock and how the use of unix timestamp in small expiration examples, doesn't expire the cached items as expected.
=> port code from yii2 handling memcached issue, related to use of unix timestamp

framework/web/CHttpSession.php
Fixes bug introduced in #4308 (https://github.com/yiisoft/yii/pull/4308#pullrequestreview-479712334)
=> Allow setting samesite correctly when calling setCookieParams()

composer.json
This allows you to do: `composer require yiisoft/yii ~1.1@dev`
=> Set composer branch alias

CHANGELOG, framework/web/helpers/CHtml.php
| Breaks BC?    | ✔️
| Fixed issues  | #4317
=> Added special option 'encode' to `$htmlOptions` argument in `CHtml::errorSummary` and `CHtml::error`

CHANGELOG, framework/db/schema/pgsql/CPgsqlSchema.php
| Tests pass?   | **requires confirmation**
| Fixed issues  | https://github.com/yiisoft/yii/issues/4294, https://github.com/yiisoft/yii/issues/4302
This PR replaces the implementation in https://github.com/yiisoft/yii/issues/4297 with an improved implementation according to the notes in https://www.postgresql.org/docs/12/release-12.html:
> - Remove obsolete pg_constraint.consrc column (Peter Eisentraut)
> This column has been deprecated for a long time, because it did not update in response to other catalog changes (such as column renamings). The recommended way to get a text version of a check constraint's expression from pg_constraint is pg_get_expr(conbin, conrelid). …
=> Add postgresql 12 support

CHANGELOG, framework/db/schema/mssql/CMssqlCommandBuilder.php
If a tablename as string is given the following error occurs: 
Error: Call to a member function getColumn() on string 
Normal CDBCommand (Mysql) does this just fine.
| New feature?  |❌
=> Fixed issue: createUpdateCommand does not accept just a table name when using MSSQL

CHANGELOG, framework/web/CHttpRequest.php
Fixes `strtr() expects parameter 1 to be string, array given (vendor/yiisoft/yii/framework/base/CSecurityManager.php:641)` error in case of malformed requests (bots may try different things in order to find vulnerability, sending array as CSRF token in one of them).
=> Prevent fatal errors while validating CSRF token of malformed requests

CHANGELOG, framework/logging/CFileLogRoute.php
| Fixed issues |  #4382
I don't really like silencing these errors, but this PR keeps the behavior exactly backward compatible.
(Yii 2 would throw an InvalidConfigException in this case: https://github.com/yiisoft/yii2/blob/master/framework/log/FileTarget.php#L111)
=> Preserve previous behavior which silently discards errors when fopen fails on PHP 8.0

composer.json
This prevents blocking of generating API documentation for site:
- https://github.com/yiisoft-contrib/yiiframework.com/blob/798f4197c4700749ce37eb8a95f648bab59f0b5c/Makefile#L76
```
- Installing cweagans/composer-patches (1.7.1): Extracting archive
cweagans/composer-patches contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "cweagans/composer-patches" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]
```
=> Allow "cweagans/composer-patches" in composer.json

CHANGELOG, framework/utils/CFileHelper.php
`GLOB_BRACE` constant is not supported on Alpine Linux. See https://github.com/docker-library/php/issues/719
Fortunately, this is the only place in the codebase, where `GLOB_BRACE` is being used. The other one being in tests:
https://github.com/yiisoft/yii/search?q=GLOB_BRACE
=> Remove GLOB_BRACE for Alpine

CHANGELOG, framework/web/CHttpRequest.php
Addition to #4386. This removes PHP 8.1 deprecation warning on `preg_match_all`
=> Fix php 8.1 warning

CHANGELOG, framework/web/helpers/CHtml.php
In PHP 8.1 I am receiving the error below when using CActiveForm checkbox field, when the CFormModel model attribute has a default 'null' value as defined. 
"strcmp(): Passing null to parameter #2 ($string2) of type string is deprecated"
The 'null' value is passed to the checkBoxList() method as the second argument variable $select.  A null value is not allowed in PHP 8.1 in strcmp().  An additional condition check for !empty() on the $select variable will prevent this error, as well as support the remaining variable types for a string or array.
=> PHP 8.1 support for active checkbox list

CHANGELOG, framework/caching/CFileCache.php
=> PHP 8.1 compatibility fix for CFileCache

CHANGELOG, framework/db/schema/mssql/CMssqlCommandBuilder.php, tests/framework/db/schema/CMssqlCommandBuilderTest.php, tests/framework/db/schema/CMssqlTest.php
Generate the correct SQL for MSSQL 11 (2012) and newer, see #4491.
| Fixed issues  | #4491
=> Fix limit and offset not working correctly with MSSQL

CHANGELOG, framework/db/schema/mssql/CMssqlPdoAdapter.php, framework/db/schema/mssql/CMssqlSqlsrvPdoAdapter.php
The return type for lastInsertId() method needs to be compatible with PDO::lastInsertId().  Adding the return type for stiring|false resolves the compatibility issue encountered in PHP 8.1
=> PHP 8.1 deprecation error, add return type for CMssql-classes

CHANGELOG, framework/i18n/CLocale.php, framework/utils/CDateTimeParser.php, framework/utils/CFormatter.php, framework/validators/CDateValidator.php, framework/validators/CStringValidator.php, framework/web/helpers/CHtml.php, framework/web/widgets/CStarRating.php, tests/bootstrap.php, tests/framework/base/CSecurityManagerTest.php, tests/framework/i18n/CLocaleTest.php, tests/framework/utils/CDateTimeParserTest.php, tests/framework/utils/CFormatterTest.php, tests/framework/validators/CFileValidatorTest.php, tests/framework/web/helpers/CHtmlTest.php, tests/framework/web/widgets/CAutoCompleteTest.php, tests/framework/web/widgets/CMaskedTextFieldTest.php, tests/framework/web/widgets/CMultiFileUploadTest.php, tests/framework/web/widgets/CStarRatingTest.php, tests/framework/zii/widgets/CGridViewTest.php, tests/framework/zii/widgets/CListViewTest.php, tests/framework/zii/widgets/grid/CButtonColumnTest.php, tests/framework/zii/widgets/jui/CJuiButtonTest.php
Re-enabled deprecation errors in tests and fixed them.
Main fixes:
- CStarRating widget throwing a deprecation error if it is initalized without `value`;
- `strcmp`, `strtolower`, `mb_stringtolower`, `mb_strpos` and other built in functions being passed  `null` in tests;
- CFileValidatorTest testing for the wrong value, it returns 0 as the outcome is always cased to an int. The test never failed because `assertEquals` uses `==` and performs type coercion;
- CStringValidator treating `null` as an empty string, `strlen(null)` is deprecated so a cast is needed;
- ClientScript tests using a reference to an uninitialised variable, for example: https://github.com/yiisoft/yii/blob/1c6f6fe221404de9afeb32059e6671676237482c/tests/framework/web/widgets/CAutoCompleteTest.php#L31 causing a deprecation …
=> Fix PHP 8.1 deprecation errors

CHANGELOG, framework/web/filters/CHttpCacheFilter.php
Fixes #4484 Set lastModified after setting cache control header,refactor duplicate code in CHttpCacheFilter::prefiler().
| Fixed issues  | #4484
=> Set Last-Modified after sending cache control headers

CHANGELOG, framework/console/CConsoleCommand.php, framework/web/actions/CAction.php
| Fixed issues  | #4516, #4518
Fixes type checking on union and intersection types in `CAction`  and `CConsoleCommand`
=> Fix type checking on union and intersection types

CHANGELOG, requirements/views/el/index.php
The requirements view file for Greek had a few class strings translated, which was wrong. This pull request fixes this.
=> FIX: incorrectly translated messages for Greek in requirements view

CHANGELOG, framework/test/CDbFixtureManager.php
When a fixture can't be loaded, you only get a generic error telling you which fixture can't be loaded, it would be more helpful if in that message we get the cause of the error
`1) Unit\RequestApiTest::testCreate
CException: Exception loading row req1 in fixture /var/www/html/test/yiitools/protected/tests/fixtures/requests.php` 
to
`1) Unit\RequestApiTest::testCreate
CException: Exception loading row req1 in fixture /var/www/html/test/yiitools/protected/tests/fixtures/requests.php Error: CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1691576897' for column 'date_added' at row 1`
| Fixed issues …
=> Show cause of the error when fixture can't not be loaded

README.md
Update the docs to show that the current php version 8.2 is supported, showing 8.1 it might give the impression that yii does not support current versions of php.
=> Update PHP supported version from 8.1 to 8.2

CHANGELOG, framework/gii/components/Pear/Text/Diff.php, framework/gii/components/Pear/Text/Diff/Engine/native.php, framework/gii/components/Pear/Text/Diff/Mapped.php
| Fixed issues  | https://github.com/yiisoft/yii/issues/4534
=> Fix pear diff php deprecations

build/commands/markdown/MarkdownParser.php, docs/viewer/components/MarkdownParser.php
Fix use of access to string using curly brackets https://www.php.net/manual/en/migration74.deprecated.php
Replaces with square brackets.
=> minor Fix deprecations: curly string access

framework/i18n/CLocale.php
=> fix/static method getCanonicalID should not be called dynamically

CHANGELOG, framework/web/widgets/captcha/CCaptcha.php
Reopened PR https://github.com/yiisoft/yii/pull/4546
=> fix/static method Imagick::queryFormats should not be called dynamically

CHANGELOG, framework/console/CConsoleCommand.php
PHP8.1 compatibility fixed.
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /opt/phishing/versions/5.3/web/protected/framework/console/CConsoleCommand.php on line 232
=> PHP 8 compatibility: Fix passing null to string parameter parameter

.github/workflows/build.yml, tests/bootstrap.php, tests/framework/db/CDbCommandTest.php, tests/framework/web/helpers/CJSONTest.php
This makes it more clear what error reporting level is being used.
=> CI tests using development ini

CHANGELOG, framework/caching/CRedisCache.php
This PR updates the Redis connection configuration to use a Unix socket (e.g. /var/run/redis/redis.sock) instead of a hostname/port.
=> Add socket connection support to CRedisCache.php
