- framework/messages/nl/yii.php
> Update Dutch translation

- framework/utils/CDateTimeParser.php
lowercase h calls formatHour12 which prints the time in 12 hour format.
> documentation error

- framework/validators/CRangeValidator.php
Added example to range validator.
I don't found anywhere actual example of range validator, that's why i decided to add it.
Hope this place - is the best for it...
> Dev 20150529 kovpak CRangeValidator phpdoc

- CHANGELOG
- framework/zii/widgets/CBreadcrumbs.php
Numeric labels in CBreadCrumbs reindex after using array_merge fix
> Fixed #3879

- framework/base/CApplication.php
Added CApplication::format getter and accessor with @property for IDE autocomplete.
> Added CApplication::format getter and accessor

- CHANGELOG
- framework/base/CComponent.php
- framework/collections/CListIterator.php
- tests/framework/base/NewComponent.php
Modify CComponent to handle if an eventHandler has been removed while iterating over the event handlers.
fixes #1191
> Fix for 1191 (detachEventHandler causing undefined index in CListIterator)

- docs/guide/test.fixture.txt
> Updated PHPUnit Fixtures documentation link

- composer.json
No one needs demos and concatenated stuff through composer.
> Make composer package lighter

- CHANGELOG
- framework/vendors/README.html
- framework/vendors/zend-escaper/Escaper.php
- framework/vendors/zend-escaper/LICENSE.md
- framework/web/helpers/CJavaScript.php
- tests/framework/web/helpers/CHtmlTest.php
- tests/framework/web/helpers/CJavaScriptTest.php
> Fixed `CJavaScript::quote()` to properly escape Unicode characters

- CHANGELOG
- framework/validators/CExistValidator.php
- framework/validators/CFileValidator.php
- framework/validators/CUniqueValidator.php
- framework/web/helpers/CHtml.php
> Reworked model error escaping to escape on output rather than in validators directly

- .travis.yml
- CHANGELOG
- composer.json
- framework/db/ar/CActiveFinder.php
- tests/travis/memcache-setup.sh
Fixes PHP 7.2 "count()" issue.
| Tests pass?   | yes (as far as "count()" concerns)
| Fixed issues  | #4167 
About the tests ...
- Travis-ci fails for PHP 7.2 because of another issue regarding "ini_set()". #4184
- It also reports 4 failures in CHtmlTest::testValue for PHP 7.2. #4186 
- I'm not really sure if **ALL** possible errors regarding "count()" could have been fixed. The unit tests may have overlooked some of them.
> Fix PHP 7.2 "count()" issue. #4167

- framework/web/CHttpSession.php
| Tests pass?   | 
| Fixed issues  | #4168
> #4168: improved session freezing

- framework/db/ar/CActiveRecord.php
> Add missing null type in CActiveRecord PHPDoc

- CHANGELOG
- framework/web/CHttpSession.php
- framework/web/filters/CHttpCacheFilter.php
(cherry picked from commit b6306908cfcd59d84269739ea3bd845de78c8be1)
> add \CHttpSession::setCacheLimiter

- CHANGELOG
- framework/web/CController.php
@samdark as per your request (https://github.com/yiisoft/yii/issues/4167#issuecomment-381564554)
| Fixed issues  | #4167
> Fix #4167 for PHP 7.2 incompatibility of count() in renderDynamic().

- CHANGELOG
- framework/web/CHttpRequest.php
- framework/yiilite.php
> CVE-2018-14773. Drop support for HTTP_X_REWRITE_URL.

- CHANGELOG
- framework/web/CHttpSession.php
> to freeze session before changing ini settings

- composer.json
> Suggest mcrypt polyfill

- CHANGELOG
- framework/logging/CProfileLogRoute.php
> PHP 7.2 Replaced create_function in CProfileLogRoute, fixes #4220

- .travis.yml
> WIP: Test against PHP 7.3

- .travis.yml
- tests/travis/memcache-setup.sh
> Skip memcache extension load on php 7.3

- .travis.yml
- CHANGELOG
- framework/validators/CEmailValidator.php
- framework/validators/CUrlValidator.php
- framework/vendors/htmlpurifier/HTMLPurifier.standalone.php
| Tests pass?   | -
| Fixed issues  | #4261
> Work around INTL_IDNA_VARIANT_2003 deprecation

- .travis.yml
- CHANGELOG
- framework/web/CHttpCookie.php
- framework/web/CHttpRequest.php
- tests/framework/web/CHttpCookieTest.php
| Is bugfix?    | no
| New feature?  | yes
| Fixed issues  | #4273
> #4273 add setcookie $options for PHP 7.3 compatibility

- .travis.yml
- tests/travis/memcache-setup.sh
| Tests pass?   | ?
| Fixed issues  | -
> Use stable PHP 7.4 on Travis

- docs/guide/quickstart.apache-nginx-config.txt
> Added NGINX Unit config to quickstart.apache-nginx-config.txt

- CHANGELOG
- framework/db/schema/pgsql/CPgsqlSchema.php
> Revert "Add PostgreSQL 12 support, rel #4294"

- .github/workflows/build.yml
> Add colors in CI

- .github/workflows/build.yml
> Repair GitHub actions

- tests/compatibility.php
Please try it out in your own environments. I have not considered other cases than CTestCase
| Breaks BC?    | ?
| Tests pass?   | ?
| Fixed issues  | #4319
> Bug fix Phpunit 9 incompatibility  1.1 (#4319)

- docs/guide/de/basics.best-practices.txt
> Fixed typo in basics.best-practices.txt

- CHANGELOG
- framework/db/CDbConnection.php
> Bug 4343. fix "driver does not support quoting" when using the driver odbc

- CHANGELOG
- framework/web/helpers/CHtml.php
- tests/framework/web/helpers/CHtmlTest.php
| Fixed issues  | #4349
Added options based on further discussion in https://github.com/yiisoft/yii/pull/4350
@rob006 Please review if you want :) I've opted to only change CHtml and keep the default/logging views (including CWebLogRoute) the same.
> Options for html5 script and style

- CHANGELOG
- framework/base/CApplication.php
- framework/console/CConsoleApplication.php
| Fixed issues  | https://github.com/yiisoft/yii/issues/4355
> Fix errorhandler missing backtrace entries

- CHANGELOG
- framework/logging/CFileLogRoute.php
> Added log file permissions

- CHANGELOG
- framework/cli/commands/shell/CrudCommand.php
- framework/cli/commands/shell/ModelCommand.php
- framework/gii/generators/model/ModelCode.php
| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/yii/issues/4369
> Fix PHP 8 warning in Gii

- CHANGELOG
- framework/caching/CRedisCache.php
> Add support for SSL to CRedisCache

- docs/guide/de/basics.application.txt
- docs/guide/de/basics.component.txt
- docs/guide/de/caching.data.txt
- docs/guide/de/caching.overview.txt
- docs/guide/de/caching.page.txt
- docs/guide/de/changes.txt
- docs/guide/de/database.ar.txt
- docs/guide/de/database.arr.txt
- docs/guide/de/database.dao.txt
- docs/guide/de/database.migration.txt
- docs/guide/de/database.overview.txt
- docs/guide/de/extension.create.txt
- docs/guide/de/extension.integration.txt
- docs/guide/de/extension.use.txt
- docs/guide/de/form.model.txt
- docs/guide/de/quickstart.apache-nginx-config.txt
- docs/guide/de/quickstart.installation.txt
- docs/guide/de/quickstart.what-is-yii.txt
- docs/guide/de/test.fixture.txt
- docs/guide/de/test.functional.txt
- docs/guide/de/test.overview.txt
- docs/guide/de/test.unit.txt
- docs/guide/de/topics.auth.txt
- docs/guide/de/topics.console.txt
- docs/guide/de/topics.error.txt
- docs/guide/de/topics.i18n.txt
- docs/guide/de/topics.performance.txt
- docs/guide/de/topics.security.txt
- docs/guide/de/topics.url.txt
- docs/guide/de/topics.webservice.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4398
Links checked
> update de lang links

- docs/guide/es/basics.application.txt
- docs/guide/es/basics.component.txt
- docs/guide/es/database.ar.txt
- docs/guide/es/database.dao.txt
- docs/guide/es/extension.use.txt
- docs/guide/es/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4400
> update es lang links

- docs/guide/fr/basics.application.txt
- docs/guide/fr/basics.component.txt
- docs/guide/fr/caching.overview.txt
- docs/guide/fr/database.ar.txt
- docs/guide/fr/database.dao.txt
- docs/guide/fr/form.model.txt
- docs/guide/fr/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4403
> update fr lang links

- docs/guide/hu/basics.application.txt
- docs/guide/hu/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4407
> update hu lang links

- docs/guide/it/basics.application.txt
- docs/guide/it/basics.component.txt
- docs/guide/it/extension.create.txt
- docs/guide/it/index.txt
- docs/guide/it/quickstart.apache-nginx-config.txt
- docs/guide/it/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4411
> update it lang links

- docs/guide/nl/changes.txt
- docs/guide/nl/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4415
> update nl lang links

- docs/guide/no/database.dao.txt
- docs/guide/no/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4417
> update no lang links

- docs/guide/pt/basics.application.txt
- docs/guide/pt/basics.component.txt
- docs/guide/pt/caching.overview.txt
- docs/guide/pt/database.ar.txt
- docs/guide/pt/database.dao.txt
- docs/guide/pt/extension.use.txt
- docs/guide/pt/form.model.txt
- docs/guide/pt/quickstart.installation.txt
- docs/guide/pt/topics.webservice.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4421
> update pt lang links

- docs/guide/pt_br/basics.application.txt
- docs/guide/pt_br/basics.component.txt
- docs/guide/pt_br/caching.overview.txt
- docs/guide/pt_br/changes.txt
- docs/guide/pt_br/database.ar.txt
- docs/guide/pt_br/database.dao.txt
- docs/guide/pt_br/database.migration.txt
- docs/guide/pt_br/extension.create.txt
- docs/guide/pt_br/extension.integration.txt
- docs/guide/pt_br/extension.use.txt
- docs/guide/pt_br/form.model.txt
- docs/guide/pt_br/quickstart.installation.txt
- docs/guide/pt_br/test.fixture.txt
- docs/guide/pt_br/test.functional.txt
- docs/guide/pt_br/test.overview.txt
- docs/guide/pt_br/test.unit.txt
- docs/guide/pt_br/topics.auth.txt
- docs/guide/pt_br/topics.webservice.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4424
> update pt_br lang links

- docs/guide/ro/basics.application.txt
- docs/guide/ro/basics.component.txt
- docs/guide/ro/caching.overview.txt
- docs/guide/ro/database.ar.txt
- docs/guide/ro/database.dao.txt
- docs/guide/ro/extension.create.txt
- docs/guide/ro/extension.integration.txt
- docs/guide/ro/extension.use.txt
- docs/guide/ro/form.model.txt
- docs/guide/ro/quickstart.installation.txt
- docs/guide/ro/topics.auth.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4426
> update ro lang links

- docs/guide/sv/basics.application.txt
- docs/guide/sv/basics.component.txt
- docs/guide/sv/caching.data.txt
- docs/guide/sv/caching.overview.txt
- docs/guide/sv/database.ar.txt
- docs/guide/sv/database.dao.txt
- docs/guide/sv/database.migration.txt
- docs/guide/sv/extension.create.txt
- docs/guide/sv/extension.integration.txt
- docs/guide/sv/extension.use.txt
- docs/guide/sv/form.model.txt
- docs/guide/sv/quickstart.apache-nginx-config.txt
- docs/guide/sv/quickstart.installation.txt
- docs/guide/sv/test.fixture.txt
- docs/guide/sv/test.functional.txt
- docs/guide/sv/test.overview.txt
- docs/guide/sv/test.unit.txt
- docs/guide/sv/topics.auth.txt
- docs/guide/sv/topics.error.txt
- docs/guide/sv/topics.i18n.txt
- docs/guide/sv/topics.performance.txt
- docs/guide/sv/topics.url.txt
- docs/guide/sv/topics.webservice.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4430
> update sv lang links

- docs/guide/vi/quickstart.installation.txt
| Fixed issues  | https://github.com/yiisoft/yii/issues/4434
> update vi lang links

- CHANGELOG
- framework/db/schema/pgsql/CPgsqlSchema.php
> Suport stripos null parameter deprecation that fixes #4456

- CHANGELOG
- framework/i18n/data/README.txt
| Fixed issues  | resolve https://github.com/yiisoft/yii/issues/4470
> fix unicode link

- docs/guide/caching.overview.txt
- docs/guide/de/caching.overview.txt
- docs/guide/fr/caching.overview.txt
- docs/guide/he/caching.overview.txt
- docs/guide/id/caching.overview.txt
- docs/guide/ja/caching.overview.txt
- docs/guide/pl/caching.overview.txt
- docs/guide/pt/caching.overview.txt
- docs/guide/pt_br/caching.overview.txt
- docs/guide/ro/caching.overview.txt
- docs/guide/ru/caching.overview.txt
- docs/guide/sv/caching.overview.txt
- docs/guide/uk/caching.overview.txt
- docs/guide/zh_cn/caching.overview.txt
- docs/guide/zh_tw/caching.overview.txt
- framework/caching/CXCache.php
| Fixed issues  | resolve https://github.com/yiisoft/yii/issues/4482
> fix xcache link

- CHANGELOG
- framework/web/auth/CWebUser.php
| Fixed issues  | https://github.com/yiisoft/yii/issues/4507
> Fix PHP 8.1 deprecation warning in CWebUser

- CHANGELOG
- framework/db/schema/pgsql/CPgsqlSchema.php
| Fixed issues  | https://github.com/yiisoft/yii/issues/4490
> Add PostgreSQL 15 compatibility

- CHANGELOG
- framework/db/schema/oci/COciSchema.php
| Fixed issues  | https://github.com/yiisoft/yii/issues/4499
> Fix PHP 8.1 deprecation warning in COciSchema

- docs/guide/topics.performance.txt
| Fixed issues  | resolve https://github.com/yiisoft/yii/issues/4555
> update docs folder links

- framework/i18n/data/README.txt
| Fixed issues  | resolve https://github.com/yiisoft/yii/issues/4557
> update framework folder links

- CHANGELOG
- README.md
| Fixed issues  | resolve https://github.com/yiisoft/yii/issues/4559
> update root folder links

- CHANGELOG
- framework/messages/cs/yii.php
> Fixed CS translation #4579

- CHANGELOG
- framework/messages/hu/yii.php
| Fixed issues  | 
There was a Hungarian translation that contained words which should not have been translated.
> fix a hungarian translation
